# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e006e25ff11001179bcc7ec940cf62dd9c4cabc00b6faf9d407d392cdacbe09266b20a2faf7a4344beac84dab7e8c1b0d5f7c948eee5ea5213bf49881ae9e75b

test:
  secret_key_base: 5b952a33f2d0d96cdbdd485a227d79f023c47d9dbeb36a400797e9f059d776afc90d68665fc1274294d170b18a7cbd5de281b9649496e7b6970c010d772e40e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
